# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LsgB22X_3pxio4Gf1apX2ZRirTDxdY0u
"""

import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import matplotlib.pyplot as plt
import seaborn as sns

book=pd.read_csv("sample.csv")

book.head()

book.nunique()

book.shape

book[['Name', 'Author', 'User Rating', 'Reviews', 'Price', 'Year', 'Genre']].sort_values(by=['Reviews'],ascending=False).head(5)

book[['Name', 'Author', 'User Rating', 'Reviews', 'Price', 'Year', 'Genre']].sort_values(by=['Reviews'],ascending=False).tail(5)

book[['Name', 'Author', 'User Rating', 'Reviews', 'Price', 'Year', 'Genre']].sort_values(by=['Price'],ascending=False).head(5)

book[['Name', 'Author', 'User Rating', 'Reviews', 'Price', 'Year', 'Genre']].sort_values(by=['Price'],ascending=False).tail(13)

plt.figure(figsize=(12,6))
sns.countplot(x='User Rating', data=book)
sns.set_context('talk')
plt.xlabel("Ratings",fontsize=20,weight='bold')
plt.ylabel("Number of Books",fontsize=20,weight='bold')
plt.title("Total Number Books in each Rating",fontsize=25)
plt.show()

book['User Rating'].value_counts()

book['User Rating'].idxmin()

book.iloc[353]

bn1=book['Name'].value_counts().head(10)

plt.style.use('seaborn-dark')
bn1.plot(kind='barh',figsize=(12,6))
sns.set_context('talk')
plt.xlabel("Frequency",fontsize = 20, weight = 'bold')
plt.ylabel("Book Names",fontsize = 20, weight = 'bold')
plt.show()

bn2=book['Author'].value_counts().head(10)

plt.style.use('seaborn-dark')
bn2.plot(kind='barh',figsize=(12,6))
sns.set_context('talk')
plt.xlabel("Frequency",fontsize = 20, weight = 'bold')
plt.ylabel("Author",fontsize = 20, weight = 'bold')
plt.show()

pd.pivot_table(book,index='Year',columns='Genre',values='Name',aggfunc='count', margins = True, margins_name='Total')

pd.pivot_table(book,index='Year',columns='Genre',values='Price',aggfunc='mean', margins = True, margins_name='Total')

pd.pivot_table(book,index='Year',columns='Genre',values='Reviews',aggfunc='sum', margins = True, margins_name='Total')

book.loc[book.groupby(['Year'])["Price"].idxmax()]

book.loc[book.groupby(['Year'])["Price"].idxmin()]

book.loc[book.groupby(['Year'])["Reviews"].idxmax()]

book.loc[book.groupby(['Year'])["Reviews"].idxmin()]

book.loc[book.groupby(['Year'])["User Rating"].idxmax()]

book.loc[book.groupby(['Year'])["User Rating"].idxmin()]

book.loc[book.groupby(['Genre','Year'])["Price"].idxmax()]

